version: 2.1

terraform: &terraform
  docker:
    - image: hashicorp/terraform

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: Validate Terraform configurations
          command: terraform validate
      - run:
          name: Check if Terraform configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi

workflows:
  version: 2
  build:
    jobs:
      - validate
